WebUI/Controllers/AuthorController.cs
using AutoMapper;
using Business.Abstract;
using Entities.Concrete;
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using WebUI.Models.AuthorModels;

namespace WebUI.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorService _authorService;
        private readonly IValidator<Author> _validator;
        private readonly IMapper _mapper;

        public AuthorController(IAuthorService authorService, IValidator<Author> validator, IMapper mapper)
        {
            _authorService = authorService;
            _validator = validator;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var authors = _authorService.GetAll();
            var authorModel = _mapper.Map<List<AuthorModel>>(authors);
            return View(authorModel);
        }

        public IActionResult Edit(int id)
        {
            Author author = _authorService.GetById(id);
            UpdateAuthorModel model = _mapper.Map<UpdateAuthorModel>(author);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(UpdateAuthorModel model)
        {
            Author author = _mapper.Map<Author>(model);
            var result = _validator.Validate(author);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);
                return View(model);
            }
            Author authorForUpdate = _authorService.GetById(model.AuthorId);
            authorForUpdate = _mapper.Map<Author>(model);
            _authorService.Update(authorForUpdate);
            return RedirectToAction("Index");

        }



        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CreateAuthorModel model)
        {
            Author author = _mapper.Map<Author>(model);

            var result = _validator.Validate(author);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);
                return View(model);
            }
            _authorService.Add(author);
            return RedirectToAction("Index");

        }


        [HttpPost]
        public IActionResult Delete(int authorId)
        {
            _authorService.Delete(_authorService.GetById(authorId));
            return RedirectToAction("Index");
        }

    }
}

WebUI/Views/Author/Add.cshtml
@{
    ViewData["Title"] = "Add";
}
@using WebUI.Models.AuthorModels
@model CreateAuthorModel

<h4 class="fw-bold py-3 mb-4">Yazarlar</h4>
<div asp-validation-summary="ModelOnly">
</div>

<div class="card mb-4 w-75 mx-auto">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Yazar Ekle</h5>
        <small class="text-muted float-end">Default label</small>
    </div>
    <div class="card-body">
        <form asp-action="Add" asp-controller="Author" method="post">
            <div class="mb-3">
                <label class="form-label" for="authorName">Yazar İsmi</label>
                <input type="text" class="form-control" asp-for="AuthorName" placeholder="Yazar İsmi">
                <span class="text-danger" asp-validation-for="AuthorName"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" for="authorSurname">Yazar Soyadı</label>
                <input type="text" class="form-control" asp-for="AuthorSurname" placeholder="Yazar Soyadı">
                <span class="text-danger" asp-validation-for="AuthorSurname"></span>
            </div>

            <div class="mb-3">
                <label for="authorState" class="form-label">Yazar Durumu</label>
                <select class="form-select" asp-for="AuthorState" aria-label="Yazar Durumu">
                    <option value="true">Etkin</option>
                    <option value="false">Devredışı</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Ekle</button>
        </form>
    </div>
</div>

WebUI/Views/Author/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@using WebUI.Models.AuthorModels
@model UpdateAuthorModel

<h4 class="fw-bold py-3 mb-4">Yazarlar</h4>
<div asp-validation-summary="ModelOnly">
</div>
<div class="card mb-4 w-75 mx-auto">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Yazar Güncelle</h5>
    </div>
    <div class="card-body">
        <form asp-action="Edit" asp-controller="Author" method="post">
            <div class="mb-3">
                <label class="form-label" for="authorName">Yazar İsmi</label>
                <input type="text" class="form-control" id="authorName" name="authorName" placeholder="Yazar İsmi" asp-for="AuthorName">
                <span class="text-danger" asp-validation-for="AuthorName"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" for="authorSurname">Yazar Soyadı</label>
                <input type="text" class="form-control" id="authorSurname" name="authorSurname" placeholder="Yazar Soyadı" asp-for="AuthorSurname">
                <span class="text-danger" asp-validation-for="AuthorSurname"></span>
            </div>

            <div class="mb-3">
                <label for="authorState" class="form-label">Yazar Durumu</label>
                <select class="form-select" id="authorState" name="authorState" aria-label="Yazar Durumu" asp-for="AuthorState">
                    <option value="true">Etkin</option>
                    <option value="false">Devredışı</option>
                </select>
                <span class="text-danger" asp-validation-for="AuthorState"></span>
            </div>
            <input type="hidden" asp-for="AuthorId" />

            <button type="submit" class="btn btn-primary">Güncelle</button>
        </form>
    </div>
</div>

WebUI/Views/Author/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using WebUI.Models.AuthorModels
@model List<AuthorModel>
<h4 class="fw-bold py-3 mb-4">Yazarlar</h4>
<div class="card">
    <h5 class="card-header">Yazar Listesi</h5>
    <div class="table-responsive text-nowrap">
        <table class="table">
            <thead>
                <tr>
                    <th>Yazar Adı-Soyadı</th>
                    <th>Durumu</th>
                </tr>
            </thead>
            <tbody class="table-border-bottom-0">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.AuthorName @item.AuthorSurname</td>
                        @if (item.AuthorState == true)
                        {
                            <td><span class="badge bg-label-success me-1">Etkin</span></td>
                        }
                        else
                        {
                            <td><span class="badge bg-label-danger me-1">Devredışı</span></td>
                        }



                        <td>
                            <div class="dropdown">
                                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                    <i class="bx bx-dots-vertical-rounded"></i>
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="/Author/Edit/@item.AuthorId"><i class="bx bx-edit-alt me-2"></i> Edit</a>
                                    <form asp-action="Delete" asp-controller="Author" method="post">
                                        <input type="hidden" name="authorId" value="@item.AuthorId">
                                        <button class="dropdown-item" type="submit"><i class="bx bx-trash me-2"></i>Delete</button>
                                    </form>

                                </div>
                            </div>
                        </td>
                    </tr>
                }


            </tbody>
        </table>
    </div>

</div>
<div class="mt-3">
    <a class="btn btn-primary" href="/Author/Add">Yazar Ekle</a>
</div>